In [ ]:
import numpy as np
class MyBDA :
    def __init__(X_src,Y_src,X_tar,Y_tar,
                 dim,bda_lambda=0.1,kernel='linear',gamma=1.0,T=10,mu=0.7,mode='bda'):
        self.X=np.hstack((np.transpose(X_src),np.transpose(X_tar)))
        self.x=np.dot(self.X,np.diag((1.0/(np.sqrt(np.sum(self.X*self.X,axis=0)))).reshape(-1)))
        self.m=self.x.shape[0]
        self.n=self.x.shape[1]
        num_src =X_src.shape[0]
        num_tar=X_tar.shape[0]
        self.e=np.vstack((1/num_src*np.ones((num_src,1)),-1/num_tar*np.ones((num_tar,1))))
        self.C=(np.unique(Y_src)).shape[0]
        self.H = np.eye(n) - 1/n * (np.ones((n,n)))
        self.M=np.dot(np.dot(e,e.reshape(1,-1)),C)
        self.acc_ite = []
        self.Y_tar_pseudo = []
    def fit(self):
        for i in range T :
            N=0
        '''
        if ~isempty(Y_tar_pseudo) && length(Y_tar_pseudo)==nt
            for c = reshape(unique(Y_src),1,C)
                e = zeros(n,1);
                if strcmp(mode,'W-BDA')
                    Ns = length(Y_src(Y_src==c,:));
                    Nt = length(Y_tar_pseudo(Y_tar_pseudo == c,:));
                    Ps = Ns / length(Y_src);
                    Pt = Nt / length(Y_tar_pseudo);
                else
                    Ps = 1;
                    Pt = 1;
                end
                e(Y_src==c) = sqrt(Ps) / length(find(Y_src==c));
                e(ns+find(Y_tar_pseudo==c)) = -sqrt(Pt) / length(find(Y_tar_pseudo==c));
                e(isinf(e)) = 0;
                N = N + e*e';
            end
        end '''
            if (mu == 1):
                mu = 0.999
            M=(1-mu)
            

In [1]:
import numpy as np
import pandas as pd
from scipy import sparse
label = pd.read_csv("../select_label.csv")
label1 = label['ID_1']
label2 = label['ID_2']
Y_src= label1.values
Y_tar= label2.values
features = pd.read_csv("../select_feature.csv")
features = features.values
X_src= features[:,1:5]
X_tar = features[:,5:9]

In [2]:
X_src=np.array([[1 ,2 ,3],
    [4 ,5, 6]])
X_tar=np.array([[7,8, 9],
   [ 10 ,11 ,12]])
Y_src=np.array([[1],
    [2]])

In [3]:
X=np.hstack((np.transpose(X_src),np.transpose(X_tar)))

In [4]:
x=np.dot(X,np.diag((1.0/(np.sqrt(np.sum(X*X,axis=0)))).reshape(-1)))

In [5]:
m=x.shape[0]
n=x.shape[1]

In [6]:
num_src =X_src.shape[0]
num_tar=X_tar.shape[0]


In [7]:
1/num_src*np.ones((num_src,1))

array([[0.5],
       [0.5]])

In [8]:
-1/num_tar*np.ones((num_tar,1))

array([[-0.5],
       [-0.5]])

In [9]:
e=np.vstack((1/num_src*np.ones((num_src,1)),-1/num_tar*np.ones((num_tar,1))))

In [10]:
C=(np.unique(Y_src)).shape[0]

In [11]:
np.eye(n)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
H = np.eye(n) - 1/n * (np.ones((n,n)))

In [13]:
M=np.dot(np.dot(e,e.reshape(1,-1)),C)

In [14]:
M

array([[ 0.5,  0.5, -0.5, -0.5],
       [ 0.5,  0.5, -0.5, -0.5],
       [-0.5, -0.5,  0.5,  0.5],
       [-0.5, -0.5,  0.5,  0.5]])

In [4]:
def kernel_bda(ker,gamma,X,X2=None):
    if(ker=='rbf'):
        nlsq=np.sum
        
        
        
    if(ker=='linear'):
        if (X2==None):
            K=np.dot(np.transpose(X),X)
        else :
            K=np.dot(np.transpose(X),X)

In [7]:
 X=[[1, 2, 3],
[4 ,5, 6]]


In [10]:

np.dot(np.transpose(X),X)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])